server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/books/**
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
